networks:
  goorm:
    driver: bridge

volumes:
  db_data:

services:
  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - goorm

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
#    environment:
#      - NEXT_PUBLIC_API_URL=/api/v1
#      - CHOKIDAR_USEPOLLING=true
#      - WATCHPACK_POLLING=true
    networks:
      - goorm
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- -H 0.0.0.0 -p 3000

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - goorm

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.backend.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
    networks:
      - goorm

