networks:
  goorm:
    driver: bridge

volumes:
  db_data:

services:
  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: Asia/Seoul
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - goorm

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
#    environment:
#      - NEXT_PUBLIC_API_URL=/api/v1
#      - CHOKIDAR_USEPOLLING=true
#      - WATCHPACK_POLLING=true
    networks:
      - goorm
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- -H 0.0.0.0 -p 3000

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      - TZ=Asia/Seoul
    networks:
      - goorm

  # Backend - Spring Boot 애플리케이션
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-dev}
      - TZ=Asia/Seoul
      - JAVA_TOOL_OPTIONS=-Duser.timezone=Asia/Seoul
    depends_on:
      - db
      - redis
    networks:
      - goorm
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/swagger-ui.html", "||", "exit", "1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    restart: unless-stopped

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./nginx/nginx.backend.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
    networks:
      - goorm

