networks:
  goorm:
    driver: bridge

volumes:
  db_data:
  app_logs:  # 애플리케이션 로그 공유 볼륨

services:
  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: Asia/Seoul
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - goorm

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - TZ=Asia/Seoul
      - JAVA_TOOL_OPTIONS=-Duser.timezone=Asia/Seoul
      - LOGGING_FILE_NAME=/app/logs/application.log
    depends_on:
      - db
      - redis
    networks:
      - goorm
    volumes:
      - ./backend/src:/app/src
      - app_logs:/app/logs  # 로그 디렉토리를 공유 볼륨으로 마운트
    command: sh -c "touch /app/logs/application.log && chmod 666 /app/logs/application.log && java -jar /app/app.jar"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/swagger-ui.html", "||", "exit", "1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      - TZ=Asia/Seoul
    networks:
      - goorm

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./nginx/nginx.frontend.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    networks:
      - goorm