spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/groom_thrid
    username: dev
    password: dev123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop # 개발용, 실행 시 테이블 초기화
    show-sql: true # 개발용, 런타임에서 로그 보기 어려우면 false로 비활성화

  flyway:
    enabled: false

server:
  port: 8080
  servlet:
    context-path: /api
  address: 0.0.0.0