# API 키 (민감 정보)
api:
  seoul:
    api-key: 4b6a64715a6a6a79313232745a596755
    url: http://openapi.seoul.go.kr:8088
    connection-timeout: 6000
    read-timeout: 10000
    bulkhead-thread-limit: 50

